version: '3'
services:
  web:
    container_name: tomcat
    build: .
    image: swe4/tomcat
    ports:
      - "8080:8080"
  db:
    container_name: mysql
    image: "mysql:8"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
